### ISSUE TITLE
Issue with Template OS Windows

### ISSUE THREAD

**Issue by CaptAintHere** [romainsi/zabbix-VEEAM_B-R#38]
If I try to link the Windows OS template to a host with the Veeam template associated, I receive the following error :
```
Discovery rule "service.discovery" already exists on "backup", inherited from another template.
```
It is because both templates have the same key `service.discovery` in discovery rules. Is there a solution to use both templates on the same host ?

**Comment by romainsi** [comment]
Hi,

I know, this problem persists...
I don't really have a solution at the moment except to record the items for veeam services manually.

Provisionally, it will be necessary to delete the item service.discovery in the OS WINDOWS template if it is not used, otherwise if you do not want the Veeam services you can remove it from the template Veeam B&R.

**Comment by Ceillian** [comment]
It seems to make sense to just remove the service discovery for Veeam and use the Zabbix Windows Template for monitoring services. As long as the Veeam services are set to automatic and you remove the exclusion from the expression, then all your Veeam services will be monitored anyways.

**Comment by mtxadmin** [comment]
I faced the same problem. Seems @Ceillian 's words are reasonable.

**Comment by podshivalovdv** [comment]
A bit late, but perhaps would be useful for others...
The workaround would be to add an alias into zabbix agent config on the host like this:
```
Alias=service.discovery[hyperv]:service.discovery
```
And then replace `service.discovery` in the Zabbix template with `service.discovery[hyperv]`

Unfortunately the "workaround" would need to be applied on all the hosts where the Zqabbix template will be used.
